Type = "jscript"
Intro = ""
Desc = ""
OnOpen = "onOpen"
OnClose = "onClose"
OnConnect = "onConnected"
OnDisconnect = "onDisconnected"
OnBroadcast = "onBroadcast"
OnAssist = "onAssist"
Channel = "pkuxkx.noob"
Timers = []
Aliases = []

[[Triggers]]
  ID = "room"
  Name = "room"
  Enabled = true
  Match = "^(> )*(\\S+) -\\s*$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnRoom"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

[[Triggers]]
  ID = "room_exits"
  Name = "room_exits"
  Enabled = false
  Match = "^    这里明显的(方向|出口)有 (.* 和 .+)。$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnRoomExits"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "roomexit"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
[[Triggers]]
  ID = "room_onlyexit"
  Name = "room_onlyexit"
  Enabled = false
  Match = "^    这里唯一的(出口|方向)有 (.*)。$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnRoomExits"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "roomexit"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""  
[[Triggers]]
  ID = "room_desc"
  Name = "room_desc"
  Enabled = false
  Match = "^.*$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnRoomDesc"
  SendTo = 0
  Sequence = 500
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "roomexit"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
[[Triggers]]
  ID = "room_obj"
  Name = "room_obj"
  Enabled = false
  Match = "^    (.+)\\((.+)\\)( <.+>){0,1}\\s*$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnRoomObj"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "roomobj"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
  [[Triggers]]
  ID = "room_objend"
  Name = "room_objend"
  Enabled = false
  Match = "^(.*)$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnRoomObjEnd"
  SendTo = 0
  Sequence = 500
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "roomobj"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
  [[Triggers]]
  ID = "player_hp"
  Name = "player_hp"
  Enabled = true
  Match = "^┌───个人状态────────────┬───────────────────┐$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerHP"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
    [[Triggers]]
  ID = "player_hpend"
  Name = "player_hpend"
  Enabled = false
  Match = "^└──────────────────────────────北大侠客行────┘$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerHPEnd"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerhp"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
[[Triggers]]
  ID = "player_hp1"
  Name = "player_hp1"
  Enabled = false
  Match = "^│【精神】\\s*(\\d+)\\s*/\\s*(\\d+)\\s*\\[(\\d+)%\\]\\s*│【精力】\\s*(\\d+)\\s*/\\s*(\\d+)\\s*\\(\\+\\s*(\\d+)\\)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerHP1"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerhp"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
[[Triggers]]
  ID = "player_hp2"
  Name = "player_hp2"
  Enabled = false
  Match = "^│【气血】\\s*(\\d+)\\s*/\\s*(\\d+)\\s*\\[(\\d+)%\\]\\s*│【内力】\\s*(\\d+)\\s*/\\s*(\\d+)\\s*\\(\\+\\s*(\\d+)\\)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerHP2"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerhp"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
  [[Triggers]]
  ID = "player_hp3"
  Name = "player_hp3"
  Enabled = false
  Match = "^│【真气】\\s+(\\d+)\\s+/\\s+(\\d+)\\s+\\[\\s*(\\d+)%\\]\\s+│【静气】\\s*(\\d+)%\\s*\\[(.+)\\]\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerHP3"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerhp"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
 [[Triggers]]
  ID = "player_hp4"
  Name = "player_hp4"
  Enabled = false
  Match = "^│【食物】\\s*(\\d+)\\s*/\\s*(\\d+)\\s*\\[(.+)\\]\\s*│【潜能】\\s*(\\d+)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerHP4"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerhp"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
 [[Triggers]]
  ID = "player_hp5"
  Name = "player_hp5"
  Enabled = false
  Match = "^│【饮水】\\s*(\\d+)\\s*/\\s*(\\d+)\\s+\\[(.+)\\]    │【经验】\\s*(\\d+)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerHP5"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerhp"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
   [[Triggers]]
  ID = "player_hp6"
  Name = "player_hp6"
  Enabled = false
  Match = "^│【状态】\\s*(\\S+)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerHP6"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerhp"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""

 
  [[Triggers]]
  ID = "player_score"
  Name = "player_score"
  Enabled = true
  Match = "^┌───人物详情────────────────────────┬───────┐$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerScore"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "system"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
    [[Triggers]]
  ID = "player_scoreend"
  Name = "player_scoreend"
  Enabled = false
  Match = "^└──────────────────────────────北大侠客行────┘$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerScoreEnd"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerscore"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
  [[Triggers]]
  ID = "player_score1"
  Name = "player_score1"
  Enabled = false
  Match = "^│\\s*(.*)\\s+(\\S+)\\((.*)\\)\\s*│[^│]+│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerScore1"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerscore"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
 [[Triggers]]
  ID = "player_score2"
  Name = "player_score2"
  Enabled = false
  Match = "^│ 膂力：\\[\\s*(\\d+)\\]  悟性：\\[\\s*(\\d+)\\]  根骨：\\[\\s*(\\d+)\\]  身法：\\[\\s*(\\d+)\\]\\s*│[^│]+│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerScore2"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerscore"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""  
 [[Triggers]]
  ID = "player_score3"
  Name = "player_score3"
  Enabled = false
  Match = "^│ 福缘：\\[\\s*(\\d+)\\]  容貌：\\[\\s*(\\d+)\\]  灵性：\\[\\s*(\\d+)\\]  胆识：\\[\\s*(\\S+)\\]\\s*│[^│]+│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerScore3"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerscore"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
   [[Triggers]]
  ID = "player_score4"
  Name = "player_score4"
  Enabled = false
  Match = "^│国籍：(\\S+)\\s*│门派：(\\S+)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerScore4"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerscore"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""  
   [[Triggers]]
  ID = "player_score5"
  Name = "player_score5"
  Enabled = false
  Match = "^│年龄：(\\S+)\\s*│师承：(\\S+)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerScore5"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerscore"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""  
   [[Triggers]]
  ID = "player_score6"
  Name = "player_score6"
  Enabled = false
  Match = "^│性别：(\\S+)\\s*│门忠：(\\S+)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerScore6"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerscore"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
[[Triggers]]
  ID = "player_score7"
  Name = "player_score7"
  Enabled = false
  Match = "^│生日：(\\S+)\\s*│出师：(\\S+)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerScore7"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerscore"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
[[Triggers]]
  ID = "player_score8"
  Name = "player_score8"
  Enabled = false
  Match = "^│婚姻：(\\S+)\\s*│叛师：(\\S+)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerScore8"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerscore"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""  
[[Triggers]]
  ID = "player_score9"
  Name = "player_score9"
  Enabled = false
  Match = "^│杀生：(\\d+)人\\s*│职业：(\\S+)\\s*│存款：(\\S*)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerScore9"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerscore"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
  [[Triggers]]
  ID = "player_score10"
  Name = "player_score10"
  Enabled = false
  Match = "^│被杀：(\\d+)次\\s*│道德：(\\d+)\\s*│武学点：(\\d+)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerScore10"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerscore"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
 [[Triggers]]
  ID = "player_score11"
  Name = "player_score11"
  Enabled = false
  Match = "^│死亡：(\\d+)次\\s*│声望：(\\d+)\\s*│国家积分：(\\d+)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerScore11"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerscore"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""
[[Triggers]]
  ID = "player_score12"
  Name = "player_score12"
  Enabled = false
  Match = "^│杀气：(\\S+)\\s*│愿望：(\\d+)\\s*│实战经验：(\\S+)\\s*│$"
  Send = ""
  ColourChangeType = 0
  Colour = 0
  Wildcard = 0
  SoundFileName = ""
  SoundIfInactive = false
  Script = "App.Core.OnPlayerScore12"
  SendTo = 0
  Sequence = 100
  ExpandVariables = false
  Temporary = false
  OneShot = false
  Regexp = true
  Repeat = false
  MultiLine = false
  LinesToMatch = 0
  WildcardLowerCase = false
  Group = "playerscore"
  IgnoreCase = false
  KeepEvaluating = false
  OmitFromLog = false
  OmitFromOutput = false
  Inverse = false
  Italic = false
  Variable = ""  
