(function(){
    return {
        "west":"east","w":"e",
        "north":"south","n":"s",
        "east":"west","e":"w",
        "south":"north","s":"n",
        "up":"down","u":"d",
        "down":"up","d":"u",
        "enter":"out",
        "out":"enter",
        "northeast":"southwest","ne":"sw",
        "southeast":"northwest","se":"nw",
        "southwest":"northeast","sw":"ne",
        "northwest":"southeast","nw":"se",
        "northup":"southdown","nu":"sd",
        "eastup":"westdown","eu":"wd",
        "southup":"northdown","su":"nd",
        "westup":"eastdown","wu":"ed",
        "northdown":"southup","nd":"su",
        "eastdown":"westup","ed":"wu",
        "southdown":"northup","sd":"nu",
        "westdown":"eastup","eu":"wd",
    }
})()