world.Note("加载游戏信息")
App.Load("info/rooms.js")
App.Load("info/paths.js")
App.Load("info/patrols.js")
App.Load("info/mapper.js")
App.Load("info/item.js")
App.Load("info/presets.js")
App.Load("info/blocker.js")
App.Load("info/answer.js")
App.Load("info/sell.js")
App.Load("info/ui/ui.js")

