world.Note("加载核心代码")
App.Load("core/init.js")
App.Load("core/state.js")
App.Load("core/params.js")
App.Load("core/automaton.js")
App.Load("core/options.js")
App.Load("core/connect.js")
App.Load("core/food.js")
App.Load("core/room.js")
App.Load("core/player.js")
App.Load("core/item.js")
App.Load("core/npc.js")

App.Load("core/send.js")
App.Load("core/move.js")
App.Load("core/maze.js")
App.Load("core/vehicle.js")
App.Load("core/response.js")
App.Load("core/check.js")
App.Load("core/busy.js")
App.Load("core/auth.js")
App.Load("core/captcha.js")
App.Load("core/ask.js")
App.Load("core/sleep.js")
App.Load("core/snapshot.js")
App.Load("core/task.js")
App.Load("core/command.js")

App.Load("core/task/queue.js")
App.Load("core/produce.js")
App.Load("core/proposal.js")
App.Load("core/puzzle.js")
App.Load("core/traversal.js")
App.Load("core/shoppingmode.js")
App.Load("core/combatmode.js")

App.Load("core/quest.js")
App.Load("core/hud.js")
App.Load("core/help.js")

