world.Note("加载核心代码")
App.Load("core/connect.js")
App.Load("core/room.js")
App.Load("core/player.js")
App.Load("core/item.js")
App.Load("core/send.js")
App.Load("core/move.js")
App.Load("core/response.js")
App.Load("core/check.js")
App.Load("core/prepare.js")
App.Load("core/busy.js")
App.Load("core/task.js")

App.Load("core/task/queue.js")
