App.Quest={}
App.Load("quest/wd/wd.js")
App.Load("quest/wdj/wdj.js")
App.Load("quest/dazuo/dazuo.js")
App.Load("quest/dz/dz.js")
App.Load("quest/tuna/tuna.js")
App.Load("quest/study/study.js")
App.Load("quest/caiyao/caiyao.js")
App.Load("quest/lianyao/lianyao.js")
